name: PR Checks
on:
  pull_request:
    branches:
      - main
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Download dependencies
        run: go mod download
      - name: Lint
        run: make lint TIMEOUT=5m
      - name: Test
        run: make test
      - name: Build
        run: make build
